### ISSUE TITLE
WiFi respones 

### ISSUE THREAD

**Issue by darklordbrock** [merdok/homebridge-webos3#10]
This plug in is very nice, thank you for working on it. 

Wanted to know if you have your TV connected with Wireless or cabled with ethernet? 

I have mine just connected with Wifi, the TV will turn on but it will not respond that it turned on or not.

**Comment by merdok** [comment]
Hi, 
i have my tv connected over WiFi and everything works fine. Could you more describe your issue?

**Comment by darklordbrock** [comment]
Sure.

After configuring the MAC address and IP, which i have set to a static on my router, when I try to turn the tv on with the home app on iOS. The TV will turn on but it will not respond and show that it is on in the home app. Trying to change the volume just shows no response. 

If the tv is turned on with the remote and I look in the home app it is not showing as on.

**Comment by merdok** [comment]
Thanks for the info. Well, i can't reproduce such issues on my device but i will have a look at it and see if i can do something about it. But at first it looks more likely to me like an issue with your setup. 
Could you check if the same happens over LAN cable?

**Comment by darklordbrock** [comment]
In finally got some time to work on this, and I did get it working noticed that the TV was prompting from accepting permission. Once approved it worked great. But I have found it is prompting each time the server reboots. Do you know how to find the keyFile? I'm hoping adding the keyFile will stop the prompts each time. I was looking in the TV settings with out luck and searching the internet on how to find it. 

Thank you.

**Comment by merdok** [comment]
Hi,
thanks for letting me know. 
You can configure the location where you want to save the keyFile in the config, just use the keyFile field for that and specify a path.
Greets
