### ISSUE TITLE
Allow volume service to be optional

### ISSUE THREAD

**Issue by LP0101** [merdok/homebridge-webos3#11]
Maybe have it set as a parameter inside the accessory (ie: volume: true or something).

I have an optical soundbar, so the volume can't be controlled anyway. It just causes some issues by occasionally sending the mute command to the TV when I turn off everything.

**Comment by merdok** [comment]
I was already thinking about it, i will do some tests and maybe implement that.

**Comment by merdok** [comment]
Volume service is now optional

**Comment by Dexwell** [comment]
@merdok I think you forgot to bump the version number!

**Comment by merdok** [comment]
It's not yet on npm. I will submit it later today.
