### ISSUE TITLE
Open application?

### ISSUE THREAD

**Issue by realdannys** [merdok/homebridge-webos3#14]
Any chance we could add an option for opening apps on the TV? Plex, Netflix, Custom app etc?

**Comment by merdok** [comment]
Indeed, i will think about it. But i am not sure how to include custom apps configured by the user since i somehow the app id needs to be provided to the button...

**Comment by realdannys** [comment]
I think the best way would be for the user to add each app they want as an accessory one by one.

This Alexa implementation sorts out how to do custom app ID's - https://github.com/akhan23wgu/amazon-alexa-lg-tv so something like that would work.

**Comment by merdok** [comment]
Yes, well that could be a possibility. I will think about it and see what is the best way to do it. Thanks!

**Comment by Night3lf** [comment]
+1 This feature would be awesome, I use IPTV so it would make life so much easier.

**Comment by merdok** [comment]
I will probably implement it like the external source switch, where you can switch between an application of your choice and live tv.

**Comment by merdok** [comment]
Just implemented that. Please update and check if it works as desired :)

**Comment by Night3lf** [comment]
@merdok It works great, thank you! But is there a way to set up multiple "buttons"?

**Comment by merdok** [comment]
No, currently not.
