### ISSUE TITLE
TV turned on but no status arriving back

### ISSUE THREAD

**Issue by mcnahum** [merdok/homebridge-webos3#15]
Hello,
When I activated my switch on homekit, the TV turn ON
but I've a "No response" error

when I check the logs:

[2018-2-1 23:33:35] [OLEDtv] webOS3 TV state: Off

So off course I can only turn it ON ... (I'm not using the volume options as I've a SONOS speaker there...)

any idea what I setup wrong?

**Comment by merdok** [comment]
Maybe it was just a network lag? Doesn't happen normally... The state should update automatically in the background anyway.

**Comment by mcnahum** [comment]
Pretty good network, wired connected...
I will prototype on RPi instead Docker to see if it change something..
Is there a difference on TVs?

**Comment by merdok** [comment]
There should not be any...

**Comment by quacktacular** [comment]
I've had the same issue over the past week or so. Happens on WiFi and Ethernet connection. Tried to rise the TV and created new Homebridge instance.

Does the plugin just check status by pinging the TV?

**Comment by merdok** [comment]
The tv state is checked as soon an app or siri requests the tv state. So even if the app doesn't show that the tv is on right away, it will for sure return the correct state on the next request.

If you want to get a more detailed state then just try to enable the flag **pollingEnabled**, this will ping the tv in a interval so you should get always an up to date state.

**Comment by quacktacular** [comment]
That's what I thought. With polling enabled getting some weird results though. Confirmed that I can ping the TV from the same machine without any trouble.

```
[2018-2-3 10:52:20] Homebridge is running on port 51002.
[2018-2-3 10:52:20] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:52:23] [TV Bert] webOS3 error Error: connect EHOSTUNREACH 10.0.1.25:3000
[2018-2-3 10:52:26] [TV Bert] webOS3 connecting to TV
...
[2018-2-3 10:56:46] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:46] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:56:47] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:48] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:56:48] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:49] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:49] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:56:51] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:51] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:51] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:52] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:53] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:56:53] [TV Bert] webOS3 connecting to TV
[2018-2-3 10:56:53] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:56:54] [TV Bert] webOS3 connecting to TV
...
[2018-2-3 10:57:31] [TV Bert] webOS3 error Error: Sec-WebSocket-Accept header from server didn't match expected value of 4NihDIAgNR+PCCrYDCFkAAqmNCM=
[2018-2-3 10:57:31] [TV Bert] webOS3 connected to TV
[2018-2-3 10:57:36] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:57:41] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:57:46] [TV Bert] webOS3 TV state: Off
[2018-2-3 10:57:51] [TV Bert] webOS3 TV state: Off
```

Once the TV is actually ON, the plugin reports that it is off over and over.

**Comment by mcnahum** [comment]
honestly that look to be exactly the same...I also activated the flag pollingEnabled and it's always give me the state of message.

I'm using that homebridge for netatmo too and it's working. the turn on is working, it's really an issue to have the status back

**Comment by quacktacular** [comment]
Same for me. I can use the plugin to turn the TV on, but Siri always says the TV isn’t responding. Then I can’t use it to turn it off because the state is stuck

**Comment by mcnahum** [comment]
ok good to not be alone... ping it's ok, any idea how to debug?

**Comment by quacktacular** [comment]
Ok.. so at least on my end the ping library isn't working right. The isAlive was always false. Weird.

I made this change to use tcp-ping instead (have to require it at the top and install obviously)
```
webos3Accessory.prototype.checkTVState = function(callback) {
  var self = this;
  tcpp.probe(this.ip, 3000, function(err, available) {
    if (!available) {
      self.connected = false;
    } else {
      self.connected = true;
    }
    self.log('webOS3 TV state: %s', self.connected ? "On" : "Off");
    callback(null, self.connected);
  });
}
```

That makes the state correct, and I can power the TV off. Now though I can't turn the TV back on once its off.. and the logs keep saying connecting. So weird maybe LG changed something? @merdok any ideas? :)

**Comment by quacktacular** [comment]
@mcnahum have you restarted your router recently? After making the change to tcpp ping and restarting my router it seems to be working reliably. 

Not sure why the router reboot made a difference?

**Comment by merdok** [comment]
Well the ping library is working good on my setup. I got it working with pollingEnabled 24/7 since i pushed that commit and no issues. 

Maybe it is a network issue? Do you have assigned a static IP address to your TV?

**Comment by quacktacular** [comment]
It doesn’t look like a network issue since sending a ping from the terminal works as expected. 

Have static IPs on Ethernet and WiFi.

**Comment by quacktacular** [comment]
Ok so I took with wireshark and looks like the TV is dropping / ignoring the ICMP pings intermittently. Tried with another router and having the same issue--maybe only some versions of WebOS are impacted and that why you aren't having trouble? 

Would you be open to using tcp-ping instead? Its a lightweight package and might work little more broadly. If not I can fork properly.

TCP ping utility for node.js. You can test if chosen address accepts connections at desired port and find out your latency. Great for service availability testing.

> **Why not ping wrapper?**
> It's much faster than ping tool (as soon as connection gets accepted, it's dropped and a new measure is conducted immediately), so there's no unnecessary waiting between requests.
> It allows you to test a specific service, not the whole connection
> Some servers drop ICMP echo without any response, even when online. TCP can work in such cases.
https://www.npmjs.com/package/tcp-ping

**Comment by merdok** [comment]
What TV and webos version do you have?

**Comment by quacktacular** [comment]
I have an OLED55C7P on 04.70.36

**Comment by mcnahum** [comment]
I've a an oled55e6 running webOS 05.30.10. (not sure how you know the exact version of WebOS)
The ping seams robust here... technically I've 2 routers between TV and Office but usually not causing any issue.

**Comment by merdok** [comment]
So it seems that it is not a ping issue... The webOS version you find in the TV settings screen under TV information.

**Comment by quacktacular** [comment]
Mine is webOS 3.5 yes.

**Comment by merdok** [comment]
Maybe it is an issue with webOS 3.5 then...

**Comment by mcnahum** [comment]
So I have webOS 3.3.3-3704 (dreadlocks-dharug)

**Comment by merdok** [comment]
So the ping issue seems like a webOS 3.5 issue. I also have the webOS 3.3.3 and ping works fine here.
I will do some testing with **tcp-ping** on my device. 
@quacktacular does tcp-ping still work fine on your tv? Did you use it 24/7?

**Comment by quacktacular** [comment]
Yes it’s still working fine. One thing I noticed is that the TV continues to respond to pings for about a minute after turning off (and therefore shows as on in Homebridge). Other than that it’s been great.

**Comment by merdok** [comment]
Oh, really? That is not good when the TV still responds for a short time after turned off... That also leaves a margin of error...
Well, i will do some tests on my TV with tcp-ping.

**Comment by quacktacular** [comment]
That’s true, but it is working much better than before. I’m assuming it waits to go to sleep for a bit. Wouldn’t it be nice if LG just have us an endpoint for state? Haha

**Comment by merdok** [comment]
Ok, I will do some tests this week with this.
Maybe in webOS4...

**Comment by merdok** [comment]
@quacktacular 
@mcnahum 
Just replaced ping with tcp-ping, please update and let me know if it works better :)

**Comment by mcnahum** [comment]
ok, so the result is strange ... that's the exact reverse of before...
the result is the TV discovered as always ON... so I can now turn it off ... I mean the TV go off. But the status (on the logs and on homekit) stay always on ...

**Comment by quacktacular** [comment]
@mcnahum exactly the same here. I think the TV keeps the network up for 1 min after its turned off for some reason. Maybe it helps things get going faster if was turned off by accident.

If you need to turn back on right away, though, you can just press "turn off" again in HomeKit and quickly turn back on. 

@merdok thanks for making the change this is definitely an improvement :) Maybe we'll be able to find a better way to get state in the future, but this works really well as is. I've even got it working with homebridge-alexa! Haha.

**Comment by merdok** [comment]
@mcnahum @quacktacular That is still strange, as far as i tested my TV doesn't respond to the ping after i turn it off....

I'm glad that it works better now . If some issues come in the future then let me know and i will have a look!
