### ISSUE TITLE
Mobile TV setting

### ISSUE THREAD

**Issue by efp1** [merdok/homebridge-webos3#16]
Hi guys,

Can't find the "Mobile TV" setting on my TV. Is my tv not supported? I have the 49UB850V.

**Comment by merdok** [comment]
It should be under "General". You could try if it works without it but i am not sure about it.

**Comment by eukiseioh** [comment]
I don’t have “mobile Tv” setting on my TV but this plugin works for me on my WebOS 1.0
I can turn off, set volume and mute but i can’t turn on the TV from standby. Why?

**Comment by merdok** [comment]
Yes, "mobile TV on" is not supported on webOS1, so the TV cannot listen in standby for incoming packets. So you will not be able to turn it on.
