### ISSUE TITLE
Can sometimes turn on TV, but sometimes cannot

### ISSUE THREAD

**Issue by thehauntedmattress** [merdok/homebridge-webos3#17]
I have your plugin working with a webOS 3 LG TV.  If I manually turn on the TV using the actual remote, I can turn it off and then immediately turn it back on within a few minutes using Homekit.  But if I let a few hours go by, attempting to turn on the TV using Homekit says that it is unresponsive.  Any way to fix this issue?  Thanks.

Edit: The TV is connected through Wi-fi and not ethernet, if that makes a difference.

**Comment by merdok** [comment]
From my experience WiFi doesn't make a difference, it should work as good as Ethernet.  Try to enable polling by setting the flag **pollingEnabled** to true in the config. This should improve state detection.

**Comment by thehauntedmattress** [comment]
It’s enabled.

**Comment by merdok** [comment]
Then i will suspect that indeed your network connection could be the issue. When the TV is on and the TV status is off then something with your network is not correct. Maybe your TV ip address is not static?

**Comment by thehauntedmattress** [comment]
When the TV is on the status is correct.

**Comment by merdok** [comment]
Huh? Bu you just said that the TV status is off...

**Comment by thehauntedmattress** [comment]
Sorry.  Let me try to re-explain this now that I am now longer on mobile.  When the TV is on (assuming it was turned on with its own remote and not Homekit), Homekit reflects that it is on.  I can adjust volume, I can change the input with your newly updated release, and I can turn off the TV, all via Homekit.  If I turn the TV off via Homekit, it will turn off.  If I immediately afterwards turn it back on, it will turn on via homekit.  However, if I let a few hours pass by, and attempt to turn it on again via Homekit, it will not turn on.  Homekit always displays the correct status of the TV, whether it is off or not.  **What I am having trouble with is turning on the TV via homekit several hours after it was on.**  Mobile TV is enabled in the TV settings.

Here is my config file text.

>       "accessory": "webos3",
      "name": "LG TV",
      "ip": "192.168.2.76",
      "mac": "48:8D:36:D7:60:42",
      "keyFile": "/home/pi/.homebridge/lgtv-",
      "pollingEnabled": true,
      "externalInput": true,
      "externalSource": "HDMI_1"


So in terms of static IP addresses, neither my router nor my TV are set to receive static IP addresses; however the way my router works is that it gives out "'static" IP addresses anyway (meaning everything is set to DHCP, but the router assigns the same IP to the same MAC address everytime).

**Comment by merdok** [comment]
It sounds for me like a network issue or your mac address could be wrong. Maybe also something blocking the magic packets (firewall, antivirus)?
The tv is turned on by simply sending a magic packet in the network to the specified mac address.

**Comment by thehauntedmattress** [comment]
But why is it that I can sometimes turn on the TV via HomeKit, but other times I can’t?  The MAC address is not wrong; just verified it.  The IP address is always 2.76.  If something was blocking packets why is it only for the ON (some of the time), and not the other actions?

**Comment by askovi** [comment]
@thehauntedmattress If the switch and bridge become unresponsive after a few hours, something is idling on the machine where you're running homebridge. Make sure you don't have any settings enabled to power off any peripherals to save electricity, etc. Also check your firewall rules. 
When you see it as unresponsive are you still getting pollings in the console? 

Related to the suggestion above, you can also try reserving that local ip to the TV's mac address in your router config.

**Comment by thehauntedmattress** [comment]
I do still get pollings on the console.  The console is always polling.  Which firewall settings am I supposed to check?  The firewall on the Pi 0W that I’m running Homebridge on, the router, or the TV?  And what port numbers I am checking?

**Comment by merdok** [comment]
Port 7/9 UDP are used for magic packets. Your issue is strange and i have never experienced that, maybe some other homebridge plugin is freezing your homebridge?

**Comment by thehauntedmattress** [comment]
This is my list of Homebridge Plugins:

- homebridge-webos3
- homebridge-samsungsmarttv
- homebridge-roomba690
- homebridge-platform-wemo v1.3.6
- homebridge-config-ui-x v2.5.1
- homebridge-alexa

**Comment by merdok** [comment]
Can't tell if any of those could the issue. You would need to test it out yourself, maybe also update homebridge?

**Comment by merdok** [comment]
Does the issue still exists?

**Comment by thehauntedmattress** [comment]
Yes it does.  No idea what else to try.

**Comment by merdok** [comment]
This has most probably nothing to do with the plugin, i would say that something is wrong with your setup.

**Comment by thehauntedmattress** [comment]
How recent is this newest update to the plug-in?

**Comment by thehauntedmattress** [comment]
By the way in terms of this new update I am having a few more issues.

1. I keep getting this message: webOS - error Error: EACCES: permission denied, open '/home/pi/.homebridge/lgtv-' for the key file (it requires me to hit yes for the permissions every time the Pi is rebooted).
2. The app switching does not work.  I have my app set to com.webos.app.netflix but it will not switch to netflix.  The TV will however, exit Netflix if I turn off the switch.
3. If I have the appSwitch configuration field enabled, then externalSourceSwitch does not show up as a Homekit button anymore.

Would adding multiple inputs and apps work as separate buttons or is it limited to one app and/or one input?

**Comment by thehauntedmattress** [comment]
Update: I have fixed issue 2 and 3.  I currently just have issues with the key file.  I am wondering if maybe because the key file is not being stored that maybe this is the reason why sometimes the TV does not turn on from the Home app?  Thanks.

**Comment by merdok** [comment]
This error usually comes when you don't correct access rights to the specified directory. You would need to correct your permissions. Your user needs write permission in the  specified directory.

**Comment by thehauntedmattress** [comment]
Hey I actually fixed that error by moving that file to /var/homebridge.  But I am still having the issue that started this thread.

**Comment by merdok** [comment]
I think that issue is not related to the plugin but to your setup. Turning on the tv just sends a magic packet in the network, so either something is blocking this magic packet or it gets lost due to unstable network,

**Comment by thehauntedmattress** [comment]
The problem is where and how would I even start troubleshooting that?

**Comment by merdok** [comment]
Maybe find a tool to send Wake on LAN (Magic packets) and try if the tv wakes up constantly.

**Comment by Patrick-Ber** [comment]
i have the same problem ... sometimes it work good .. sometimes it work not.
And Sometime , if i want power off, the plugin think the tv is on 

Here a short copy of the status 

Feb 23 22:01:17 hbridge2 homebridge[5135]: [2018-2-23 22:01:17] [Fernseher] webOS - TV state: On
Feb 23 22:01:18 hbridge2 homebridge[5135]: [2018-2-23 22:01:18] [Fernseher] webOS - TV state: On
-> Try to power off
Feb 23 22:01:19 hbridge2 homebridge[5135]: [2018-2-23 22:01:19] [Fernseher] webOS - disconnected from TV
Feb 23 22:01:19 hbridge2 homebridge[5135]: [2018-2-23 22:01:19] [Fernseher] webOS - TV state: On
Feb 23 22:01:20 hbridge2 homebridge[5135]: [2018-2-23 22:01:20] [Fernseher] webOS - TV state: On


and i think the tv is not off, only in a deep sleep ?


But sometimes i have no problems ...

and here is my config .

  {
      "accessory": "webos3",
      "name": "Fernseher",
      "ip": "MY IP ADRESS",
      "mac": "MY MAC ADRESS",
      "keyFile": "/home/pi/lgtvKeyFile",
      "pollingEnabled": true,
      "pollingInterval": 1,
      "externalSourceSwitch": "HDMI_2",
      "appSwitch": "netflix"
    }

**Comment by thehauntedmattress** [comment]
What I think is going on is the fact that the TV's turn off the network interface card when in standby after a certain period of time.  This explains why if I shut off my TV and turn it on right away it works, but like after an hour it does not turn on if it already off.  However, I do have "turn via wi-fi" enabled so I don't know why this is the case.  I have the LG 49UJ6200 that I bought in December 2017, and I am curious if maybe this is something with newer TV's.

**Comment by Patrick-Ber** [comment]
hmm. i think somethink is wrong.
i turn my tv off with my remote control , but the status of homebridge say already ;

Feb 23 22:50:17 hbridge2 homebridge[5135]: [2018-2-23 22:50:17] [Fernseher] webOS - TV state: On.

and after a reboot of homebridge (TV is off) the same .
Feb 23 22:55:00 hbridge2 homebridge[1259]: [2018-2-23 22:55:00] [Fernseher] webOS - connected to TV
Feb 23 22:55:00 hbridge2 homebridge[1259]: [2018-2-23 22:55:00] [Fernseher] webOS - TV current appId:
Feb 23 22:55:00 hbridge2 homebridge[1259]: [2018-2-23 22:55:00] [Fernseher] webOS - TV current appId:
Feb 23 22:55:00 hbridge2 homebridge[1259]: [2018-2-23 22:55:00] [Fernseher] webOS - TV muted: No
Feb 23 22:55:01 hbridge2 homebridge[1259]: [2018-2-23 22:55:01] [Fernseher] webOS - TV state: On



Then 5 Minute after TV ist off.
I can turn it again on with homebridge.
But some error i see at log .

Feb 23 22:59:16 hbridge2 homebridge[1597]: [2018-2-23 22:59:16] [Fernseher] webOS - error Error: connect ECONNREFUSED 192.168.28.93:3000

but sometimes, it work without any problem ;
Turn TV OFF 

Feb 23 23:03:06 hbridge2 homebridge[1597]: [2018-2-23 23:03:06] [Fernseher] webOS - TV state: On
Feb 23 23:03:07 hbridge2 homebridge[1597]: [2018-2-23 23:03:07] [Fernseher] webOS - disconnected from TV
Feb 23 23:03:07 hbridge2 homebridge[1597]: [2018-2-23 23:03:07] [Fernseher] webOS - TV state: Off

and TV is off ...

**Comment by thehauntedmattress** [comment]
These are the messages from my logs that I get: [2/23/2018, 5:19:10 PM] [LG TV] webOS - TV state: Off

And I get them every 5 seconds as I have polling enabled.

**Comment by Patrick-Ber** [comment]
i hope merdok can fix it ...

**Comment by thehauntedmattress** [comment]
Here's the thing.  I don't think it's Merdok's issue or homebridge-webos3's issue.  And I say that because while trying to diagnose this issue, I have downloaded another app that can send a magic packet to devices to wake them up called WakeMeOnLan.  This app can only wake up that TV if it has been recently turned or off but not after a while.  So the issue is really with the TV itself and WebOS.  What I need is a way to have the TV not turn off the network interlace card or wi-fi.
Now the way I have homebridge setup, is the Raspberry Pi 0W that is running it, it actually connected to that same TV via HDMI.  I have already tried the HDMI-CEC Homebridge plugin and that didn't either for some other reason.  I have also tried going ethernet to the TV from the Pi itself (through a USB to ethernet adapter), and that didn't work either.  I think both the ethernet port and the wi-fi are shutoff after certain amount of time of the TV being on standby.

**Comment by Patrick-Ber** [comment]
my problem is ... is the TV longtime ON ... this plugin work not correctly . If i try to turn of the TV with EVE App, i do not work. And if it turn off with remotecontroll the plugin say webOS - TV state: On though my TV is OFF. 

But it´s only if the TV longer as 5 Minutes ON.

**Comment by merdok** [comment]
Like i suspect this is not an issue with the plugin but with some hardware. Most probably something with the TV itself. 
@thehauntedmattress @Patrick-Ber Do you connect your TVs to LAN or WiFi? Maybe try a different connection? Do you both have the UJ TV series?

**Comment by Patrick-Ber** [comment]
i use only LAN (with a Gigabit switch). it is a oled xxb7d series. the lg remote app work without any problems.

**Comment by Yatr** [comment]
i have same as Patrick-Ber problem.
if i have **"pollingEnabled": true**, then webOS think that TV is "on" after i tuned it off.

> [2018-2-24 11:26:00] [TV] webOS - TV current appId: com.webos.app.hdmi1
> [2018-2-24 11:26:00] [TV] webOS - TV volume: 15
> [2018-2-24 11:26:00] [TV] webOS - TV muted: No
> [2018-2-24 11:26:03] [TV] webOS - TV state: On
> [2018-2-24 11:26:08] [TV] webOS - TV state: On
> [2018-2-24 11:26:13] [TV] webOS - TV state: On
> [2018-2-24 11:26:18] [TV] webOS - TV state: On
> [2018-2-24 11:26:23] [TV] webOS - TV state: On
> [2018-2-24 11:26:28] [TV] webOS - TV state: On
> [2018-2-24 11:26:31] [TV] webOS - TV state: On
> [2018-2-24 11:26:31] [TV] webOS - disconnected from TV
> [2018-2-24 11:26:33] [TV] webOS - TV state: On
> [2018-2-24 11:26:38] [TV] webOS - TV state: On
> [2018-2-24 11:26:43] [TV] webOS - TV state: On
> [2018-2-24 11:26:48] [TV] webOS - TV state: On
> [2018-2-24 11:26:53] [TV] webOS - TV state: On
> [2018-2-24 11:26:58] [TV] webOS - TV state: On

If **"pollingEnabled": false** - webOS works fine, but homekit dont know if TV "ON" or "OFF".
My config:

>      {
>            "accessory": "webos3",
>            "name": "TV",
>            "ip": "XXXXX",
>            "mac": "XX",
>            "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
>            "pollingEnabled": true,
>            "appSwitch": "megogo.hd"
>         } 

TV - Oled65b6.

**Comment by sweetw0r** [comment]
I am able to turn on TV every time if it was turned off less than hour ago. I noticed that my router shows my TV as disconnected (connection is WiFi) 

My config:
```
{
    "accessory":"webos3",
    "name":"LG Ultra TV",
    "ip":"X.X.X.X",
    "mac":"X:X:X:X:X:X",
    "keyFile":"/var/homebridge/lgtvKeyFile",
    "pollingEnabled":true,
    "pollingInterval":5,
    "appSwitch":[
        "youtube.leanback.v4",
        "com.webos.app.hdmi2",
        "com.webos.app.hdmi1"
    ]
}
```

**Comment by thehauntedmattress** [comment]
@sweetw0r I think the problem is because the TVs turn off the network interface cards after a specific time.  I don't know how long it takes to do that since doing testing on that would be very impractical.  I am trying to go through the HDMI-CEC route since the Pi running homebridge is connected to my LG TV using HDMI.  The only issue I am having is the fact that my permissions won't allow CEC-Client to run when using systemd to start homebridge.

**Comment by sweetw0r** [comment]
I did the testing. It takes about an hour for TV to stop network interface. Is there a way we can keep the connection on? Also it doesn’t explain why polling isn’t showing.

**Comment by merdok** [comment]
It should not be an issue when the tv turns off the network interface. WOL (Wake On LAN) should still work as long as you have "Mobile TV On" enabled in your TV settings.

**Comment by thehauntedmattress** [comment]
Does this plugin send a wake on lan command to turn the tv on?

**Comment by sweetw0r** [comment]
Mobile TV is on. Should Wake On LAN work for WiFi as well?

**Comment by thehauntedmattress** [comment]
Mobile TV is on for me as well.

**Comment by sweetw0r** [comment]
@thehauntedmattress While perusing the thread it seems like your "homebridgeDirectory" is "/var/homebridge". If so, then we have that in common. And from what I understood it is out of the ordinary. Maybe that is something to begin with?..

**Comment by thehauntedmattress** [comment]
I really think its the TV and not the plugin.  The plugin works flawlessly when the TV is on.

**Comment by sweetw0r** [comment]
Found this https://www.depicus.com/wake-on-lan/wake-on-lan-for-apple-mac Let's see if it helps to test Magic packet out

**Comment by sweetw0r** [comment]
Ok TV was offline:
<img width="712" alt="screen shot 2018-04-03 at 10 43 35 pm" src="https://user-images.githubusercontent.com/12688470/38290585-d318f616-3790-11e8-80b4-16ad82bf1cf8.png">
It got ON from 2nd attempt to run the wolcmd

**Comment by thehauntedmattress** [comment]
Is your tv connected via wi-fi or Ethernet?

**Comment by sweetw0r** [comment]
The TV was offline:
<img width="712" alt="screen shot 2018-04-03 at 10 43 35 pm" src="https://user-images.githubusercontent.com/12688470/38290704-6863c82c-3791-11e8-9349-ca4efc2632e4.png">

It got on after 2nd attempt!
I use WiFi only @thehauntedmattress

**Comment by sweetw0r** [comment]
This morning (when  8 hours passed) I wasn’t able to switch the TV on neither via HomeKit nor via the wolcmd:(

**Comment by thehauntedmattress** [comment]
@merdok Is there a way to send the wake on lan command through the pi's ethernet and not the WLAN if it doesn't do so already?  I think the solution to my problem is connecting my pi via ethernet to my TV.  If I can send a wake on lan command through ethernet, then it should work.  I have already changed my mac address to the TV's MAC, but it still isn't turning on.

**Comment by thehauntedmattress** [comment]
It still won't accept the magic packet even through ethernet after being off for a while.  I proved this by sending an SSH wake on lan command.  However I believe I have my solution that incorporates [this plugin](https://github.com/zb0th/homebridge-ssh) and CEC-Client.

**Comment by merdok** [comment]
Then it seems that this must be an issue with newer TVs, i don't have any other explanation for that behavior...

**Comment by thehauntedmattress** [comment]
Yeah I guess you can this close this issue then.

**Comment by merdok** [comment]
I close it for now, but i will continue to investigate this.

**Comment by sweetw0r** [comment]
@merdok it’s Model: 49UH6100

To summarize:
Something is causing the TV to stick around longe than hour and be registered as offline device for a router and yet still accessible for WOL to turn on. If longer then 2 hours it goes to deep sleep and can’t be woken up by WOL but by CEC HDMI and RC.

Can we send anything to it periodically to keep it awake?

**Comment by sweetw0r** [comment]
It was always on. Was trying to trigger it. No difference. Wonder why native LG app doesn’t have WOL feature. Maybe there is same reason behind this.

**Comment by mikebronner** [comment]
I'm seeing this issue as well with 60UJ6300.

**Comment by thehauntedmattress** [comment]
I think for my situation the TV turns off the network card after being in standbye after an hour, so my solution involves HDMI CEC.

**Comment by thehauntedmattress** [comment]
The only solution that worked for me was to actually connect the Raspberry Pi running homebridge to the TV via HDMI.  I then used a homebridge SSH command to turn on the TV using a homebridge CEC command.

**Comment by lonksheep** [comment]
@thehauntedmattress

I have my Pi connected to TV....

If tomorrow I post up my config can you help me insert the relevant jsconfig info into mine? 

I’ve managed to get my existing JSConfig working fine but every time I try and add other accessories/ platforms my code is always wrong :-( I’m quite the duffer! 

I’ll install all the relevant packages from your link.

**Comment by thehauntedmattress** [comment]
Yeah so here's what you need to install.  I was actually mistaken about one of the plug-ins.  The Homebridge CEC plug-ins never worked for me.  This is why I am using an SSH command along with [CEC Utils](https://medium.com/@timleland/raspberry-pi-turn-tv-on-off-cec-9c998c1a0f9b) to do this.  Here are the steps:

1. Install [CEC Utils](https://medium.com/@timleland/raspberry-pi-turn-tv-on-off-cec-9c998c1a0f9b)
2. Install [Homebridge-SSH](https://github.com/zb0th/homebridge-ssh)
3.  Below is the code for your config.json



```
 "accessories": [
          {
            "accessory": "SSH",
            "name": "name of accessory",
            "on": "echo on 0 | cec-client -s -d 1",
            "off": "echo 'standby 0' | cec-client RPI -s -d 1",
            "ssh": {
                "user": "piuser",
                "host": "pihostname",
                "port": 22,
                "password": "insertpassword"
            }
        }
    ]
```

4. In the Home app on an iOS device, this will appear as a new switch.  What I did is I combined the webOS on/off switch and this switch as one.  When you press the new combined switch on, it should turn the TV on and off.  It also even will know the state of on and off too.  

All of this should work.  I hope I am not missing any other steps.  Good luck!  Let me know if you have any more questions.

**Comment by lonksheep** [comment]
Thanks again for your time.

So..... my current Config looks like the piece below.... what I am yet to
work out properly is how to insert a new accessory.  I think I am always
getting the syntax wrong etc.... how do I copy and paste what you sent me
into the config I have below?  Hopefully if I can get this, something may
click and I can start adding loads of other accessories!

{
  "accessories" : [
    {
      "name" : "lgtv",
      "accessory" : "webostv",
      "appSwitch" : [
        "com.webos.app.tvguide",
        "youtube.leanback.v4",
        "com.webos.app.hdmi1",
        "com.webos.app.hdmi2",
        "com.webos.app.hdmi3",
        "com.webos.app.hdmi4"
      ],
      "mac" : "XX:XX:XX:XX:XX:XX",
      "keyFile" : "/home/pi/.homebridge/lgtvKeyFile",
      "pollingEnabled" : true,
      "ip" : "192.168.0.XX"
    }
  ],
  "bridge" : {
    "username" : "XX:XX:XX:XX:XX:XX",
    "name" : "Homebridge",
    "pin" : "032-45-154",
    "port" : 51826
  }
}

**Comment by thehauntedmattress** [comment]
```
{
  "accessories" : [
    {
      "name" : "lgtv",
      "accessory" : "webostv",
      "appSwitch" : [
        "com.webos.app.tvguide",
        "youtube.leanback.v4",
        "com.webos.app.hdmi1",
        "com.webos.app.hdmi2",
        "com.webos.app.hdmi3",
        "com.webos.app.hdmi4"
      ],
      "mac" : "XX:XX:XX:XX:XX:XX",
      "keyFile" : "/home/pi/.homebridge/lgtvKeyFile",
      "pollingEnabled" : true,
      "ip" : "192.168.0.XX"
    },
         {
            "accessory": "SSH",
            "name": "name of accessory",
            "on": "echo on 0 | cec-client -s -d 1",
            "off": "echo 'standby 0' | cec-client RPI -s -d 1",
            "ssh": {
                "user": "piuser",
                "host": "pihostname",
                "port": 22,
                "password": "insertpassword"
            }
        }
  ],
  "bridge" : {
    "username" : "XX:XX:XX:XX:XX:XX",
    "name" : "Homebridge",
    "pin" : "032-45-154",
    "port" : 51826
  }
}
```

Just remember the commas and brackets are so essential or it will not work.  But if this is your only config, this is a valid JSON.  Use [JSONLint](https://jsonlint.com/) to verify it works.

**Comment by lonksheep** [comment]
Absolute legend!!

I'll have to leave it a while to let the TV "reset", but I have grouped it
with my TV power switch and that seems to work fine.  I do have a yellow
exclamation above this, and wondered if that is totally normal??

**Comment by lonksheep** [comment]
Regards,

 
C D Heyworth Maj RLC I Requirements Manager Protected Mobility | Land Concept and Assessment | Elm 1a #4140 | MOD Abbey Wood | Bristol | BS34 8JH | Work Mobile: 07919302430  I Email & Skype: Christopher.Heyworth173@mod.gov.uk I Pers Mobile: 07850125338 I Pers Email: cheyworth83@gmail.com
 
Please scan QR Code below to add my contact card to your mobile device. Most devices no longer require a program to do this, just open your camera and aim at the code below. (This will only appear email originating from myself)

**Comment by lonksheep** [comment]
Lol,

Looks like we have similar problems... just looking at a thread to turn on the PS4 and saw this.....



 
Regards,

 
C D Heyworth Maj RLC I Requirements Manager Protected Mobility | Land Concept and Assessment | Elm 1a #4140 | MOD Abbey Wood | Bristol | BS34 8JH | Work Mobile: 07919302430  I Email & Skype: Christopher.Heyworth173@mod.gov.uk I Pers Mobile: 07850125338 I Pers Email: cheyworth83@gmail.com
 
Please scan QR Code below to add my contact card to your mobile device. Most devices no longer require a program to do this, just open your camera and aim at the code below. (This will only appear email originating from myself)

**Comment by thehauntedmattress** [comment]
So you are trying to turn on a PlayStation 4 that is connected to an LG TV?

**Comment by lonksheep** [comment]
Yep... I am now. I was thinking I could just use the SSH plugin.

Did you get it working ok? 

 
Regards,

 
C D Heyworth Maj RLC I Requirements Manager Protected Mobility | Land Concept and Assessment | Elm 1a #4140 | MOD Abbey Wood | Bristol | BS34 8JH | Work Mobile: 07919302430  I Email & Skype: Christopher.Heyworth173@mod.gov.uk I Pers Mobile: 07850125338 I Pers Email: cheyworth83@gmail.com
 
Please scan QR Code below to add my contact card to your mobile device. Most devices no longer require a program to do this, just open your camera and aim at the code below. (This will only appear email originating from myself)

**Comment by thehauntedmattress** [comment]
So first off, when I am not using my PS4, I always power it down completely, and do not use rest mode.  Second, my PS4 is connected to a Samsung smart TV.  I am using a Samsung TV homebridge plug-in to achieve this.  The Samsung plug-in, however, sends commands to the TV by emulating button presses from a would be remote control.  This includes buttons for switching to an HDMI source (kind of like how this LG plug-in does it).  However, if a PS4 is not on, it does not send a signal via HDMI.  This means that if the Samsung TV does not detect a source from the HDMI, it will not switch to it.  The way around this is so set up a series of button presses with a small delay between them.  The TV will also check if it is on first, and if it is not, it will turn itself on.  Afterwards it will fire the following button presses:

1. Input
2. Left (x6)
3. Right (x1)
4. Select

The reason why left needs to be pressed 6 times, is that I have 6 sources on my input.  That way it goes all the way to the first one (no matter where it is on the list), and then my PS4 is my second source.  It will then hit enter and select the HDMI source.  Then HDMI CEC will turn on the PS4.  So I know this is very complicated, but it does work.

Now it is theoretically possible for you to make it so that you turn on the TV and then switch to whatever HDMI source your PS4 is connected and use HDMI CEC to actually turn it on.

**Comment by slonoed** [comment]
For whoever has this issue: setting `broadcastAdr` field to target IP helps because packed gets to destination (if firewall is ok with it).
