### ISSUE TITLE
Accessory Not Supported

### ISSUE THREAD

**Issue by alexarena** [merdok/homebridge-webos3#22]
In the Apple Home app (and Eve) I'm seeing the "Accessory Not Supported" message.

Here's what my config looks like:
```json
        {
          "accessory": "webos3",
          "name": "My webOS tv",
          "ip": "",
          "mac": "",
          "pollingEnabled": true,
        }
```

Any ideas why this is occurring? Latest Homebridge and iOS.

Thanks in advance!

**Comment by merdok** [comment]
Maybe you installed the plugin in a local directory. When you install it, make sure that you use the -g option like `sudo npm install -g homebridge-webos3`

**Comment by alexarena** [comment]
Weirdly the fix turned out to be removing the accessory from my `config.json`, restarting Homebridge,  and then adding it back. ¯\_(ツ)_/¯

I think this may have been a Homebridge bug, not one with this plugin. Thanks for the advice, though!
