### ISSUE TITLE
More externals HDMI?

### ISSUE THREAD

**Issue by tombenetin** [merdok/homebridge-webos3#24]
Hi, it's possible set more then 1 externals HDMI for easier switching between HDMI's? Thanks

**Comment by merdok** [comment]
Currently not, but this is something that i have on my scope to implement.

**Comment by tombenetin** [comment]
Okay, thanks so much for fast reply and for this plugin, i like it

**Comment by Kimovitzh** [comment]
This would be great!

Multiple appSwitch and externalSourceSwitch would be awesome!

**Comment by merdok** [comment]
@tombenetin 
@Kimovitzh 
Since version 0.9.3 it is now possible to specify more external sources. Please try it and let me know if it works as desired.

**Comment by tombenetin** [comment]
It's work like charm. it's possible to set custom names of this switches?

**Comment by tombenetin** [comment]
Sure, but everytime when i restart my raspberry rename it back, but it's not big problem :) thanks again
