### ISSUE TITLE
"Some of your devices are not responding" response for TV.

### ISSUE THREAD

**Issue by asm09fsu** [merdok/homebridge-webos3#25]
Just curious, is anyone else seeing this issue specifically when using this plugin? I have polling enabled and the interval set to 5.

Steps:
Me: "Hey Siri, turn on the TV"
Siri: "Sending request…"
< TV turns on >
Siri: "Some of your devices are not responding."

Same when turning off the TV.

**Comment by merdok** [comment]
I noticed that too. Sometimes it happens but i am not yet sure why. But as far as i know it doesn't affect the functionality of the plugin, just the response sometimes comes...
Anyway i will keep an eye on this and see if i can fix that in the future.

**Comment by overbog** [comment]
The broadcast address is not provided to wol. This is required when there are multiple network interfaces. In these situations, the device can not be switched on.

**Comment by merdok** [comment]
@overbog could you give me some more details about it? What do you mean with broadcast address? By multiple network interfaces you mean when the TV is connected through LAN and WiFI at the same time?

**Comment by asm09fsu** [comment]
@overbog That's quite interesting. When I get home tonight I'll see if I am connected via both WiFi and LAN (I'm pretty sure I am, actually).

**Comment by overbog** [comment]
Hello,
   First thanks for the great job.
   In case of multiple interfaces on the device running homebridge. (mine has).

   About broadcast address: https://en.wikipedia.org/wiki/Broadcast_address <https://en.wikipedia.org/wiki/Broadcast_address> The WOL magic packet is sent to a broadcast address. By default it uses 255.255.255.255. 
   This should work in most cases, but if there is more than one interface the system needs a more specific broadcast address:

[bogdan@nucu ~]$ ifconfig
em1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.10.254  netmask 255.255.255.192  broadcast 10.10.10.255
        inet6 fe80::c23f:d5ff:fe62:9e17  prefixlen 64  scopeid 0x20<link>
        ether c0:3f:d5:62:9e:17  txqueuelen 1000  (Ethernet)
        RX packets 297340775592  bytes 406981691746909 (370.1 TiB)
        RX errors 1  dropped 54803  overruns 0  frame 1
        TX packets 442725890333  bytes 604711881033983 (549.9 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7c00000-f7c20000  

em1.443: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.188  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::c23f:d5ff:fe62:9e17  prefixlen 64  scopeid 0x20<link>
        ether c0:3f:d5:62:9e:17  txqueuelen 0  (Ethernet)
        RX packets 46322206  bytes 5950407888 (5.5 GiB)
        RX errors 0  dropped 135472  overruns 0  frame 0
        TX packets 70549671  bytes 53460565510 (49.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

My LG TV is connected via em1.443 interface. We can se interface for default broadcast address used is wrong (em1).
[bogdan@nucu wake_on_lan]$ ip route get 255.255.255.255
broadcast 255.255.255.255 dev em1  src 89.32.222.254 
    cache <local,brd> 

   Here is my dirty solution:
   I’ve changed the following line in /homebridge-webos3/node_modules/wake_on_lan/wake_on_lan.js
   var address     = opts['address']     || ‘255.255.255.255'	
   with
   var address     = opts['address']     || '192.168.2.255'

   In my case 192.168.2.12 is the address of LG TV and 192.168.2.255 is the broadcast address but is setup dependent. There may be a way to obtain it from TV or from homebridge server like this:
[bogdan@nucu ~]$ ip route get 192.168.2.12
192.168.2.12 dev em1.443  src 192.168.2.188 
    cache 
[bogdan@nucu ~]$ ifconfig em1.443
em1.443: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.188  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::c23f:d5ff:fe62:9e17  prefixlen 64  scopeid 0x20<link>
        ether c0:3f:d5:62:9e:17  txqueuelen 0  (Ethernet)
        RX packets 46324706  bytes 5950834240 (5.5 GiB)
        RX errors 0  dropped 135487  overruns 0  frame 0
        TX packets 70551673  bytes 53460735320 (49.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[bogdan@nucu wake_on_lan]$ 
My JavaSript knowledge is very limited and I do not know how can it be done with node.

   
About multiple interfaces on TV. My TV does not support WOL via wireless.

There may be another reasons for power ON failures as we can se on this thread: https://community.home-assistant.io/t/power-on-webos-tv/4756/23

As English is not my nattive language, please excuse any errors on my part.

Bogdan Timofte

**Comment by asm09fsu** [comment]
@merdok since this seems to be a package issue, should we look at a different WOL package? Seems like the one you use is a few years old

**Comment by overbog** [comment]
Hello,
  It’s not a WOL package issue. It just need more information. The broadcast address can also be computed from IP and Subnet Mask using a tool like https://github.com/ericlagergren/node-ipcalc <https://github.com/ericlagergren/node-ipcalc> .
  

Bogdan Timofte

**Comment by asm09fsu** [comment]
@overbog I understand, however your changes were changes for the node-wake-on-lan package, which is a sub-package of this package

**Comment by merdok** [comment]
As far i as i understand it, it is an issue related to the node-wake-on-lan package which is a dependency. If there is another WOL package which supports that functionality then i can gladly include it.

**Comment by overbog** [comment]
Hello again.

I wrote a patch to add netmask config parameter, compute the broadcast address and pass it to WOL module:

--- ./index.js.orig	2018-03-01 01:02:27.577280106 +0200
+++ index.js	2018-03-01 01:14:35.805650901 +0200
@@ -1,6 +1,7 @@
 const lgtv2 = require('lgtv2');
 const wol = require('wake_on_lan');
 const tcpp = require('tcp-ping');
+const {IPv4} = require('ctr-ipaddr');
 
 let Service, Characteristic;
 
@@ -15,6 +16,8 @@
     this.log = log;
     this.ip = config['ip'];
     this.name = config['name'];
+    this.netmask = config['netmask'] || '0.0.0.0';
+    this.broadcast = new IPv4(this.ip, this.netmask).broadcast;    this.name = config['name'];
     this.mac = config['mac'];
     this.keyFile = config['keyFile'];
     this.volumeControl = config['volumeControl'];
@@ -258,7 +261,7 @@
 webos3Accessory.prototype.setState = function (state, callback) {
     if (state) {
         if (!this.connected) {
-            wol.wake(this.mac, (error) => {
+            wol.wake(this.mac, { address: this.broadcast}, (error) => {
                 if (error) return callback(new Error('webOS - wake on lan error'));
                 this.checkCount = 0;
                 setTimeout(this.checkWakeOnLan.bind(this, callback), 5000);

This works for me without any change to WOL module. The netmask is available in the TV menu.

Further research for power on failures may include tweaking of the flowing WOL parameters.
    , num_packets = opts['num_packets'] || 3
    , interval    = opts['interval']    || 100
but for me it works just fine with defaults.
Bogdan Timofte

**Comment by asm09fsu** [comment]
@overbog can you submit your fix as a PR?

**Comment by merdok** [comment]
@overbog  I am still not sure what it has to do with this issue and for what use cases does it help?
As far as i know understood it, it helps people who connected their TV using both WiFi and LAN at the same time?

**Comment by overbog** [comment]
Hello,

   I'm sorry but I do not know how to do it.

**Comment by overbog** [comment]
Helo,

> @overbog <https://github.com/overbog> I am still not sure what it has 
> to do with this issue and for what use cases does it help?
It helps when the device on which the homebridge runs has multiple 
network interfaces. In these cases, without specifying the address, the 
WOL package is sent WAN interface, while the TV is usually connected via 
LAN interface.
> As far as i know understood it, it helps people who connected their TV 
> using both WiFi and LAN at the same time?

At least in my case the TV disconnects from the wifi when it is turned 
off so I do not see any possibility to send the startup command via the 
wifi connection.

**Comment by asm09fsu** [comment]
I am currently connected via LAN and am seeing this issue.

**Comment by merdok** [comment]
@overbog The TV WiFi doesn't disconnect when you turn off the TV as long as you have the "Mobile TV on" option enabled. At least the WiFi still listens for the WOL package when the TV is off. This could maybe be different on older WebOS TVs.

@asm09fsu only via LAN? I think if you are only connected via LAN then you should not have the issue...

**Comment by overbog** [comment]
My TV started to shutdown wireless interface this January. Until then worked just fine with phone LG TV app via wifi. FW version is 5.30.10. No update available. "Mobile TV“ is on, but that is between me and LG :)

**Comment by merdok** [comment]
Well i have the same firmware version and everything works fine, WiFi doesn't shutdown.

**Comment by asm09fsu** [comment]
@merdok What iOS version do you have running on your Apple TV / HomePod? I've got a non-4k Apple TV running 11.3 beta, and the home pod running 11.2.6 (or whatever is in production). Trying to see if this is an overall Homebridge issue

**Comment by overbog** [comment]
**First:**
  Let's ignore my wifi off issue since it can be a model/country specific behavior. And has nothing to do with this plugin.

**Then:**
My apple tv 4th generation version is 11.2.6.

**Now:**
It's clear that we are talking about two or more different issues here:
1: My case
  Multihomed homebridge (pi or whatever device is running on): My patch solved the problem for me.
2: asm09fsu case
  Failures when trying to power On/0ff Since it manifests in both cases we exclude a WOL issue.
  There are some questions here.
  - It happens all the time? @merdok says he noticed that behavior sometimes... 
  - Is this reproducible using Home app? Siri may fail to identify the right service and try to use mute switch.
  - What about other apps. I've noticed that sometimes my Home app gets out off sync with accessories states with my other plugins too. I'm using Elgato Eve in those cases because it has an accessory view that can be refreshed on demand.

**Comment by merdok** [comment]
@asm09fsu I don't have an Apple TV nor a HomePod. I use an iPad as my Home hub.

@overbog what do you mean by "Multihomed homebridge"? You have more then 1 homebridge server running?

The WOL magic packet is only relevant for turning ON the TV, for turning off internal TV commands are used.

I sometimes noticed the behavior that the TV doesn't respond when asking Siri about the status, but the TV turning ON always works for me.

**Comment by asm09fsu** [comment]
I have the issue when turning on the TV about 90% of the time.

**Comment by overbog** [comment]
@merdok [Multihoming](https://en.wikipedia.org/wiki/Multihoming)
Multihomed homebridge was a bad choice. The device that runs homebridge is multihomed.
Ex: In my case (for energy efficiency) homebridge is running on a Mini PC Intel® NUC connected to many networks as it serve multiple other purposes: router, web/database server, NVR, NAS, etc and it's shared with one of my neighbors soo it's connected to multiple networks.
And yes it runs 2 homebridge instances each on different network but this is not so relevant. Once you have more than 1 one interfaces WOL needs to know where to send the request.

About Siri. Is not available in my language. Works fine for me (when recognize my accent), turning the TV on or off each time.

I've noticed an unexpected behavior:
Hey Siri!
TV status
---"Checking around the house"
--Toggles TV power state.
---"Sorry, I didn't hear back from your devices"

Hey Siri!
TV status?
---Tell me the status (as expected).

So if does not that there is a question,  tries to do something(no idea what) and fails... .
Here is the log for "Hey Siri/TV status" with the TV off:
TV os powered on then...
[2018-3-4 10:16:12] [TV] webOS - connected to TV
[2018-3-4 10:16:12] [TV] webOS - current appId: com.webos.app.livetv
[2018-3-4 10:16:12] [TV] webOS - TV muted: No
[2018-3-4 10:16:16] [TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of xb7ZU4jezIuRvVVXZNbFi8t9Zgc=

**Comment by overbog** [comment]
@asm09fsu I have the issue when turning on the TV about 90% of the time.
With Siri or Home app?

**Comment by merdok** [comment]
Ok, so there are 2 things which we are talking about here. Multiple WOL interfaces which are not be part of this issue, and the "device not responding issue" when using Siri which is part of this issue.

I think the issue with the WOL is so rare that it can be ignored for now, i guess not many people run the multiply interfaces on device...

There other issue, which i can confirm by myself, definitely exists and more people are affected by it. I currently don't know from what it comes but i sometimes experience is by myself.
@asm09fsu i don't think that your issue that you cannot turn on the TV in 90% of the time is related to this plugin, but more to your network or hardware.

**Comment by asm09fsu** [comment]
I will close this since we don’t want to attempt to find a resolution. If the WOL issue is still present, please open another issue.
