### ISSUE TITLE
keyFile Location

### ISSUE THREAD

**Issue by atx-eshaheen** [merdok/homebridge-webos3#27]
Hi,

I'm running my server on a Mac, so the pi directory in the config doesn't exist.  Is it possible to make that log file location adjustable so for other platforms?

Thanks,
Eric

**Comment by merdok** [comment]
Hi,

you can just set the keyFile directory to whatever you want. The directory in the in the README is just an example.

**Comment by atx-eshaheen** [comment]
Got it - thanks.  I didn’t try it because of the “Don't specify a directory or you'll get an EISDIR error.” line in the end me.

**Comment by merdok** [comment]
Of course it needs to be a file so your location can't end with a slash "/"
