### ISSUE TITLE
pollingEnabled false don't work

### ISSUE THREAD

**Issue by Fearandil** [merdok/homebridge-webos3#28]
I've set "pollingEnabled" to false, but in log I've "webOS - connecting to TV" every second

**Comment by merdok** [comment]
Make sure that you just write false, without the quotas. Also you need to reboot your homebridge after you change that value.

**Comment by Fearandil** [comment]
Sorry for the slow response. I’ve checked and false is without quote. Also added the pollingInterval to 999. Restarted many times and still log that is connecting to the TV.

**Comment by merdok** [comment]
**pollingEnabled** default value is **false**, so if you remove the property completely then it should not work, if it still works then you maybe editing the wrong config file.
