### ISSUE TITLE
How to install the package ?

### ISSUE THREAD

**Issue by AlexNoop** [merdok/homebridge-webos3#3]
Hello,
I have a LG 58UH635v TV under webos3.
I would like to test your module on my homebridge but I do not know how to do ... I confess that I do not master the installations with github ...
Can you help me please?
I would be pleased to give you feedback.
thank you.

**Comment by merdok** [comment]
Hi,

you need to download the zip file and extract it to your node_modules directory. After that add the accessory in your config.json and restart homebridge. 
I think i will add this package to npm for a simpler installation but i don't know yet when.

Greets

**Comment by summer69guy** [comment]
hi, i am placing this in my node_module directory, but when homebridge load the plugin it says i do not have the lgtv2 plugin..

can you say me the exact path of the node_modules directory please?

**Comment by merdok** [comment]
You are missing the package "wake_on_lan". You need to install it using npm.
