### ISSUE TITLE
Can't connect to tv

### ISSUE THREAD

**Issue by DinRigtigeFar** [merdok/homebridge-webos3#31]
Whenever I try to run homebridge I get this error (homebridge still runs fine though with my other devices responding):
webOS - error Error: getaddrinfo ENOTFOUND undefined undefined:3000

Config:               
        "accessories": [{
                "accessory": "webos3",
                "name": "My TV",
                "ipaddress": "XXX",
                "mac": "XXX",
                "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                "pollingEnabled": false,
                "externalInput": true,
                "externalSourceSwitch": "HDMI_3",
                "appSwitch": "com.webos.app.tvguide"
        }],

In homebridge I see this:
[My TV] webOS - connecting to TV

What can I do to fix it?

**Comment by merdok** [comment]
Property **ipaddress** doesn't exist. The property name is **ip**...

**Comment by DinRigtigeFar** [comment]
Thanks for the quick resolve. I was using an artefact accessory.
