### ISSUE TITLE
Inputs and Netflix

### ISSUE THREAD

**Issue by Magiccowinuse** [merdok/homebridge-webos3#32]
I am newer to all of this. I am comfortable successfully making changes to the coding. The problem I am trying to work through is changing the inputs you have loaded. I only have one external input (hdmi ARC) my receiver handles all other switching. I would like to be able to app switch to Netflix instead of hdmi2 and revert back to the ARC hdmi port, instead of the coaxial input, when Netflix is turned off. I would like the same control when YouTube is selected. YouTube button is currently working, just reverts to the channel input when turned off. Netflix, I cannot figure out how to add functionality to get to this app. Thanks for your help.

**Comment by merdok** [comment]
Just create multiple switches for apps which you need and then switch between them.
