### ISSUE TITLE
Wrong Status

### ISSUE THREAD

**Issue by tansuka** [merdok/homebridge-webos3#33]
Hello,

I really love the add-on, thanks for great work. 
However, after the latest update Home app shows the wrong status for the TV. When I click the switch it can turn the tv off, change switch to off position after 5 seconds switch goes on again while tv stays of. Here is the config 
`        {
            "accessory": "webos3",
            "name": "LG Television",
            "ip": "192.168.1.24",
            "mac": "ab:ab:ab:ab:ab:ab",
            "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
            "pollingEnabled": true,
            "volumeControl": false,
            "pollingInterval": 10,
            "appSwitch": [
                "com.webos.app.hdmi4"
            ]
        }` 

And here is the log:
`[4/4/2018, 9:46:40 PM] [LG Television] webOS - connected to TV
[4/4/2018, 9:46:58 PM] [LG Television] webOS - disconnected from TV
[4/4/2018, 9:49:04 PM] [LG Television] webOS - connected to TV
[4/4/2018, 9:49:04 PM] [LG Television] webOS - current appId: com.webos.app.hdmi4
**[4/4/2018, 9:49:08 PM] [LG Television] webOS - disconnected from TV**
[4/4/2018, 9:49:24 PM] [LG Television] webOS - connected to TV`

The bold part is the where I turn tv off, and in the logs it says "connected to TV" but tv is off actually. I'm pretty sure that Mac address is correct and ip is binded to it.

Thanks

**Comment by merdok** [comment]
Could you tell me step by step how to reproduce this issue so i can try it on my TV? If i can do that on my TV then it will be much more easier for me to find and fix the issue.

**Comment by tansuka** [comment]
Hello @merdok ,

I couldn't find a certain pattern, yet. Sometimes, it shows me  the wrong status as described above. 

I'll close the issue until I find a valid pattern to reproduce issue. 

Thanks for the response and for this great plugin.

**Comment by merdok** [comment]
Ok, let me know if you find a pattern.

**Comment by Wazifutz** [comment]
I came across the same issue.
When putting an LG OLED TV into standby after 4 hours of usage, it runs an algorithm to prevent image retention. I believe that it stays connected for a couple of minutes until that algorithm is completed.
