### ISSUE TITLE
appSwitch usage

### ISSUE THREAD

**Issue by quacktacular** [merdok/homebridge-webos3#35]
I want to use appSwitch to create three separate switches (for HDMI 3, AV 1, and Live TV) so I'm declaring this in my config
```
            "appSwitch": [
                "com.webos.app.hdmi3",
                "com.webos.app.livetv",
                "com.webos.app.externalinput.av1"
            ]
```
Should that work? I only see a single switch in Home app, displaying all three items comma separated. Pressing the switch changes the input once, but does not cycle through.

**Comment by merdok** [comment]
Yes, this should work. I suspect that you somewhere have a typo and instead of an array a single string is read. Please recheck your config file.

**Comment by quacktacular** [comment]
Ah looks like I miss an update! v0.9.2 -> v0.9.3 resolved this issue.
