### ISSUE TITLE
Lightbulbs

### ISSUE THREAD

**Issue by arnthorsnaer** [merdok/homebridge-webos3#4]
Hi there - this is not really an issue with this project but I am curious why you need to represent volume and mute via bulbs. Is this because of a limitation of HomeKit?

**Comment by merdok** [comment]
The integrated HomeKit app in iOS can't control volume (at least i didn't find a way to do that) for this reason i represent the volume as light bulbs. That way it can be controlled from the iOS HomeKit app and also from all other apps like Eve.

**Comment by arnthorsnaer** [comment]
Thanks
