### ISSUE TITLE
The plugin stopped working

### ISSUE THREAD

**Issue by BrauCadena** [merdok/homebridge-webos3#403]
It has been working for 1 year, but now it is not working. I tried to install it again but I am getting the error below:
![image](https://user-images.githubusercontent.com/32884256/137943825-b85198e3-d7cd-4585-8334-1be8d540c3be.png)

**Comment by merdok** [comment]
Hi, your issue has nothing to do with the plugin. Your issue is during node-gyp install(rebuild), you would need to fix that. Usually that means that your nodejs is not up to date, you might want to try update that.
