### ISSUE TITLE
Set Top Box Power Control

### ISSUE THREAD

**Issue by vipersonic** [merdok/homebridge-webos3#42]
On my LG TV remote, there is a button on the top right that says "STB PWR" which powers on my set-top box. Is there any way to implement this into the plugin? 🙂

**Comment by merdok** [comment]
I'm not sure about that. I will check that out if i can send the same command as the button the tv.

**Comment by vipersonic** [comment]
Great, thanks!

**Comment by merdok** [comment]
Sorry, i think this is not possible. At least i didn't find any way to di it...

**Comment by vipersonic** [comment]
Thanks for checking it out anyway. Appreciate it. 

Kenneth
