### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by summer69guy** [merdok/homebridge-webos3#6]
i, thanks for the plugin,

But i always got this error message http://imgur.com/a/lstIi , randomly

**Comment by merdok** [comment]
Hi,

when do you get the error? Does it somehow affects the plugin, like does the plugin stop working after the error? What TV are you using?

Greets

**Comment by sfanicola** [comment]
No error at all, since the last update! 
Everything is working! No permission request anymore after adding the keyfile
Great! Thank you
My tv is a LG 49uhv750
Best regards

Nicola

**Comment by merdok** [comment]
Good to hear! Thanks for the info!
