### ISSUE TITLE
Turning on TV freezes in Homekit

### ISSUE THREAD

**Issue by padman74** [merdok/homebridge-webos3#75]
HI Merdok, 
I'm facing a new issue. 
I want to start a specific "app" on the TV like HDMI1 but it doesn't work. It starts the TV but shows only last valid channel, it doesn't switch to the app. When the TV is on and I use the app buttons, everything works fine, it's just the starting process. When starting the app with Homekit the command ends with "no response".

Any help would be great. 
Regards, Volker

**Comment by merdok** [comment]
Well, i would guess that this has something to do with your setup. Maybe conflicts with other plugin? Do you have polling enabled?

**Comment by padman74** [comment]
How can I analyze conflicts with other plugins? I uninstalled the two last installed plugins but the failure remains.  I tried to disable the polling but without effect.

**Comment by padman74** [comment]
After reinstalling this plugin and disabling polling it works now.
