### ISSUE TITLE
Change HDMI

### ISSUE THREAD

**Issue by m11rphy** [merdok/homebridge-webos3#9]
Hi first of all great plugin and thank you for all your hard work. I was wondering if there is anyway to enhance the plugin In order to change HDMI?

**Comment by merdok** [comment]
Hi,
i suspect you mean to change the source?
Of course it would be possible, but the issue is how do you present it in a convenient way using the HomeKit app. For each source there would need to be a separate switch and i am not sure if that would be the correct way to do it.

**Comment by m11rphy** [comment]
That’s exactly how I thought it would work, each HDMI would have its own switch you could add to automations. Would be the missing piece in my HomeKit puzzle

**Comment by merdok** [comment]
Yes, that would be indeed a way to do it but since there are many sources it would just spam your setup with switches.  You have just a limited space in your control center or any other app which you use for controls.
Anyway, I can try that out and see what the results are...

**Comment by m11rphy** [comment]
That would be great if you could give it a go. I would just put the unused sources in a spare room in homekit but I see your point

**Comment by m11rphy** [comment]
Did you get a chance to try this?

**Comment by merdok** [comment]
Sorry, didn't have time yet but i have it on my todo list. Will try to spend some time on it next week.

**Comment by m11rphy** [comment]
Hey buddy, did you ever get a chance to look at this?

**Comment by merdok** [comment]
I was already experimenting on this, but could not decide about how to implement it...

**Comment by m11rphy** [comment]
Could we do a switch for HDMI? I just want to able to switch between a DVR and Apple TV via scenes in HomeKit, let me know you thoughts and thanks for all your help on this plugin

**Comment by merdok** [comment]
I think a switch is not really intuitive for changing the source... 
Switching to HDMI or other sources is easily done and that is not a problem, the problem is how to properly show this in the HomeKit app or Elgato Eve app.

**Comment by m11rphy** [comment]
A switch is the only way I can think to do this and then create a scene called "Switch to HDMI1" for example. I think that would work great with Siri

**Comment by merdok** [comment]
I will have a look at it again and try to think of something. Just can't promise when...

**Comment by mcnahum** [comment]
Just to say that I'm really interested to it too... ideally you will be able to select the HDMI you want see (I've 4 on my TV)

**Comment by merdok** [comment]
Yeah, that is why it is so problematic... There are more then 2 sources on the TV and there is no HomeKit characteristic to handle this properly.

**Comment by m11rphy** [comment]
I still think a switch for each HDMI will work. I guess the only issue is if you turn off the switch for HDMI 2 is making sure ur switches of HDMI 1

**Comment by merdok** [comment]
Yes, if you switch on one switch then you need to make sure to switch the others off...

**Comment by m11rphy** [comment]
We could achieve that via HomeKit automation I assume

**Comment by merdok** [comment]
Probably yes, but that could easily lead to bugs and each switch would need to update its state which could potentially delay response time.

**Comment by m11rphy** [comment]
Could you expose the HDMI as a scene as opposed to a switch?

**Comment by merdok** [comment]
I am not sure, i would need to check that out.

**Comment by m11rphy** [comment]
Thanks dude, I appreciate you help on this

**Comment by m11rphy** [comment]
Any more thoughts on this buddy?

**Comment by merdok** [comment]
I didn't have a chance to look into it yet. Currently busy with other tasks...

**Comment by merdok** [comment]
@m11rphy I just implemented the functionality. Please update and let me know if that is good enough for you :)

**Comment by m11rphy** [comment]
Thanks buddy, I’m in the uk will update after work 

Thanks 
Chris

**Comment by askovi** [comment]
@merdok thank you for the awesome work on this. Just installed it and I love the HDMI switch. Works well for me, I didn't even realize you literally just made it happen. Was going to ask how can we add more input sources?

**Comment by m11rphy** [comment]
@merdok am I right I thinking this won't allow us to switch between HDMI 1 and 2?

**Comment by merdok** [comment]
@m11rphy Yes, you can currently only switch between live tv and an external input of your choice. 

@askovi I will think how to optimize this in order to add more input sources. I will check the StatefulProgrammableSwitch but i didn't see a button with 3 options in Homekit yet... does such accessories exist?

**Comment by askovi** [comment]
@merdok Here's what i got for my ecobee thermostat for example: https://i.imgur.com/lIgfqsC.png
That view is triggered by the bottom left button (mode) after holding the accessory pressed (first it triggers temp adjustment). Maybe we could trigger this view directly. 
I'm open to chat and work on this together if you got time, we can hop on a discord channel or something.

**Comment by merdok** [comment]
Thanks for the info. This switch with multiple buttons would be perfect i think. I don't want to create separate buttons for each external input since this would just spam homekit with accessories and the code would grow unnecessary. 
But i will take a look at that switch for sure and see if i can implement it with it. Would be much more convenient.

**Comment by askovi** [comment]
It's true that it's less elegant with multiple switches but they don't have to spam your main homekit screen. In my setup, i made the TV into its own room and put all the controls in there (remove from favorite each one so they dissapear from main screen). If you use Siri for toggling, it doesn't matter where they are, and for manual toggling you can either go into the "TV Room" for all the switches or bind them to scenes. For example I got "Game" scene which toggles certain lights, turns TV on and could toggle HDMI_4 with the PS4 connected.

**Comment by m11rphy** [comment]
@merdok I think @askovi is right what he is saying is how I described it. I would just dump the unused switches in my junk room where I get stuff I don't really access in the home app

**Comment by merdok** [comment]
That is not just about the number of switches in homekit but also about clean code, i don't want to add 7 switches for all inputs and then another 10 for apps or so... That makes code maintaining a hell and painful. 
I find the idea with the switch with multiple buttons good and i will try to follow up on that as this could be a clean solution.

**Comment by mcnahum** [comment]
cannot be simple like "turn on TV on HDMI 1" or " turn on TV on HMDI 2" ... and "turn OFF TV"
So in the config file so set to true the switch you want to have.
so in my case I've 4 HDMI so I guess I need  6 buttons ... so with Siri "turn on APPLE TV" will do "turn on TV on HDMI 1" ...

**Comment by askovi** [comment]
So i looked into this last night. I was able to set the input switch as a thermostat, but i can't change the text on the 'mode' view from Off, heat, cool, etc. So it looks silly. I wish there was a way to customize it. 
Additionally, it constantly tries to do changes as the fake thermostat is set to a certain temperature so it tries to reach that temperature by doing the action attached to it constantly. 
So far the only one that worked rather well was the homebridge-switcheroo plugin which turned off the existing input switch before turning on the new one.

**Comment by merdok** [comment]
This generally a complicated topic since Homekit is not meant to control device in that way. That is why the necessary accessories are not there and workaround needs to be build...

**Comment by jlian** [comment]
@askovi do you have an example of how to use `homebridge-switcheroo` to control HDMI input for a webOS TV?

**Comment by askovi** [comment]
@jlian I forked the repo and added my changes here: https://github.com/askovi/homebridge-switcheroo-webos
I adapted it to work with WebOS TVs. Only tested on webos 3.5. Let me know if it works for you. 
@merdok see if you want to implement it into your plugin as well.

**Comment by jlian** [comment]
@askovi wow awesome, will try it on my webOS 4.5 TV later today. Thanks!

**Comment by mcnahum** [comment]
I finally test the HDMI option and it's interesting as the switch allow me swap between live TV & HDMI 1. so it's already covering 80% of my usage of the TV ... I'll give a try later to see if Switcheroo can be combine ...

**Comment by askovi** [comment]
@mcnahum I'm using them both right now, combined. The homebridge-webos3 for turn on and off + volume (i hid the hdmi option). And my homebridge-switcheroo-webos configured with all my devices to switch in between. Works well. Needs some more error handling in my plugin for when TV is off, etc. But for now it works.

**Comment by mcnahum** [comment]
what I'm doing wrong?
/homebridge # npm install -g homebridge-switcheroo-webos                                                                         
npm ERR! code E404                                                                                                               
npm ERR! 404 Not Found: homebridge-switcheroo-webos@latest                                                                       
                                                                                                                                 
npm ERR! A complete log of this run can be found in:                                                                             
npm ERR!     /root/.npm/_logs/2018-02-12T22_58_29_075Z-debug.log

**Comment by askovi** [comment]
It’s not on npm yet while it’s experimental until I have time to release it properly. For now you can just go on the github page and download it and put it in your npm modules folder then cd inside its folder and run npm install. Then add the config from example to your config.json and you should be good to go

**Comment by mcnahum** [comment]
I did that ... and the result I have is:

2018-2-15 10:23:24] [OLEDtv] webOS3 connected to TV                                                                             
[2018-2-15 10:23:28] [HDMI Switcher] setPowerState failed: Invalid URI "192.168.1.54HDMI_1"                                    
[2018-2-15 10:23:28] [HDMI Switcher] response: undefined                                                                         
body: undefined                                                                                                                  
[2018-2-15 10:23:35] [HDMI Switcher] setPowerState failed: Invalid URI "192.168.1.54HDMI_1"                                    
[2018-2-15 10:23:35] [HDMI Switcher] response: undefined                                                                         
body: undefined                                                                                                                  
[2018-2-15 10:23:37] [HDMI Switcher] setPowerState failed: Invalid URI "192.168.1.54HDMI_2"                                    
[2018-2-15 10:23:37] [HDMI Switcher] response: undefined                                                                         
body: undefined                                                                                                                  
[2018-2-15 10:23:38] [HDMI Switcher] setPowerState failed: Invalid URI "192.168.1.54HDMI_2"                                    
[2018-2-15 10:23:38] [HDMI Switcher] response: undefined                                                                         
body: undefined                                                                                                                  
[2018-2-15 10:23:39] [HDMI Switcher] setPowerState failed: Invalid URI "192.168.1.54HDMI_1"                                    
[2018-2-15 10:23:39] [HDMI Switcher] response: undefined                                                                         
body: undefined

**Comment by mcnahum** [comment]
the setup still not working for me ... @askovi do you have an idea how to troubleshoot it?

**Comment by askovi** [comment]
@mcnahum can you please post your config

**Comment by mcnahum** [comment]
"accessories": [
    
    {
      "accessory": "webos3",
      "name": "OLEDtv",
      "ip": "192.168.11.154",
      "mac": "xx:xx:xx:xx:xx:xx",
      "pollingEnabled": false,
      "volumeControl": false,
      "externalInput": false,
      "externalSource": "HDMI_1"
    },
    
    {
  "accessory": "Switcheroo",
  "type": "multiswitch",
  "name": "HDMI Switcher",
  "host": "192.168.1.154",
  "mac": "xx:xx:xx:xx:xx:xx",
  "multiswitch": [
     { "name" : "Apple TV"	, "path" : "HDMI_1" },
     { "name" : "PS4 Pro"	, "path" : "HDMI_2" },
     { "name" : "HDMI_3"	, "path" : "HDMI_3" },
     { "name" : "HDMI_4"	, "path" : "HDMI_4" }
  ]
}
    
    ],

Of course the mac is the good one on both case...
